In [2]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
# randn : mean 0, std 1 normal distribution
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
# if z is in between [0, 1], use BCELoss
# if z is in between (-inf, inf), use BCEWithLogitsLoss

In [3]:
# A reference to the backward propagation function is stored in grad_fn property.
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x78ffee16ded0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x78ffee16dc60>


In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0294, 0.1406, 0.0886],
        [0.0294, 0.1406, 0.0886],
        [0.0294, 0.1406, 0.0886],
        [0.0294, 0.1406, 0.0886],
        [0.0294, 0.1406, 0.0886]])
tensor([0.0294, 0.1406, 0.0886])


In [5]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad() :
    z = torch.matmul(x, w) + b
print(z.requires_grad)

True
False


In [6]:
z = torch.matmul(x, w) + b
z_det = z.detach()
print(z_det.requires_grad)

False


In [ ]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
# If 'out' is not a scalar, you need to provide the gradient argument
# to backward(), such as torch.ones_like(out).
# This is because PyTorch does not know the initial gradient (dL/dout).
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
